# Generated by Django 3.1.7 on 2021-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotasks',
            name='iscompleted',
        ),
        migrations.AlterField(
            model_name='todotasks',
            name='mark',
            field=models.BooleanField(default=False, verbose_name='Mark'),
        ),
    ]
