# Generated by Django 3.1.7 on 2021-03-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210305_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todocompleteornot',
            new_name='TodoList',
        ),
    ]
